FROM node:18-alpine

WORKDIR /backend

# COPY package.json package-lock.json ./

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .

CMD [ "node", "mailer.js" ]